// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Username string `form:"username"`
	Password string `form:"password"`

}
type Response struct {
	Message string `json:"message"`
	Users []*User
}
